name: build

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  cenpy-CI:
    name: CenPy Tests (${{ matrix.os }}, ${{ matrix.environment-file }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
        environment-file: [.ci/py36.yml, .ci/py37.yml, .ci/py38.yml]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ${{ matrix.environment-file }}
          micromamba-version: 'latest'
      
      - name: Test with pytest
        shell: bash -l {0}
        run: pytest -v cenpy
